In [5]:
import numpy as np
from random import random

In [114]:
x = np.array([[int(random()*10) for _ in range(2)] for _ in range(1000)])
print(x)
y = np.array([[i[0] * i[1]] for i in x])
print(y)

[[5 7]
 [9 4]
 [2 2]
 ...
 [3 8]
 [1 1]
 [1 0]]
[[35]
 [36]
 [ 4]
 [45]
 [28]
 [81]
 [21]
 [ 7]
 [ 4]
 [10]
 [24]
 [ 8]
 [ 0]
 [10]
 [32]
 [16]
 [28]
 [24]
 [45]
 [ 9]
 [ 6]
 [48]
 [15]
 [12]
 [64]
 [64]
 [30]
 [ 3]
 [ 3]
 [ 5]
 [ 8]
 [24]
 [18]
 [56]
 [10]
 [56]
 [ 0]
 [10]
 [ 3]
 [72]
 [32]
 [63]
 [ 2]
 [ 5]
 [ 0]
 [ 8]
 [18]
 [ 0]
 [ 3]
 [ 8]
 [ 0]
 [15]
 [ 0]
 [30]
 [ 0]
 [16]
 [16]
 [32]
 [ 0]
 [18]
 [ 6]
 [63]
 [ 5]
 [18]
 [48]
 [21]
 [30]
 [56]
 [63]
 [ 8]
 [ 3]
 [ 0]
 [24]
 [35]
 [32]
 [56]
 [36]
 [27]
 [49]
 [20]
 [ 0]
 [ 3]
 [12]
 [ 8]
 [ 6]
 [24]
 [64]
 [54]
 [ 5]
 [64]
 [16]
 [27]
 [ 2]
 [16]
 [35]
 [ 6]
 [ 4]
 [ 0]
 [ 0]
 [20]
 [30]
 [35]
 [15]
 [ 0]
 [ 3]
 [ 0]
 [20]
 [12]
 [ 0]
 [ 2]
 [36]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [10]
 [63]
 [ 9]
 [ 8]
 [24]
 [ 0]
 [18]
 [ 9]
 [32]
 [ 4]
 [14]
 [ 0]
 [ 4]
 [ 0]
 [ 0]
 [ 8]
 [45]
 [24]
 [72]
 [15]
 [36]
 [72]
 [16]
 [45]
 [ 0]
 [ 6]
 [64]
 [ 0]
 [42]
 [12]
 [10]
 [15]
 [48]
 [54]
 [14]
 [ 0]
 [18]
 [ 8]
 [12]
 [ 0]
 [ 0]
 [36]
 [14]
 [18

In [7]:
y = np.array([[i[0] ** 2] for i in x])
print(y)

[[49]
 [ 9]
 [16]
 ...
 [25]
 [ 9]
 [36]]


In [37]:
l = "te st"
arr = l.split(' ')
print(arr)

['te', 'st']


In [140]:
#input data with date,index1,homefield1,index2,homefield2
import csv
array = []
x = []
with open("/home/patrick/CK/march-madness/dataset/2019_teams_games/games.txt", 'r') as f:
    reader = csv.reader(f, delimiter=',')
    for arr in reader:
        for item in arr:
            array.append(item.strip())
i=0
while i < len(array):
    word = array[i]
    if ' ' in word:
        words = word.split(" ")
        array[i] = words[0]
        array.insert(i+1, words[1])
    i+=1

count = 0
scount = 0
arr = []
for element in array:
    if count < 8:
        arr.append(element)
        count += 1
    else:
        x.append(arr)
        count = 0
        arr = []
        arr.append(element)
        count += 1
for item in x:
    item.pop(0)
    item.pop(3)
    item.pop(5)
x = np.array(x)
print(x)

[['20181106' '269' '1' '5' '-1']
 ['20181106' '127' '1' '6' '-1']
 ['20181106' '301' '1' '7' '-1']
 ...
 ['20190405' '269' '-1' '71' '1']
 ['20190406' '329' '0' '17' '0']
 ['20190406' '295' '0' '169' '0']]


In [99]:
y = []
with open("/home/patrick/CK/march-madness/dataset/2019_teams_games/correct.txt", 'r') as f:
    reader = csv.reader(f, delimiter='\n')
    for item in reader:
        str = item[0]
        arr = str.split(' ')
        y.append(arr[0])

In [136]:
array2 = []
final = []
y = []
with open("/home/patrick/CK/march-madness/dataset/2019_teams_games/games.txt", 'r') as f:
    reader = csv.reader(f, delimiter=',')
    for arr in reader:
        for item in arr:
            array2.append(item.strip())
i=0
while i < len(array2):
    word = array2[i]
    if ' ' in word:
        words = word.split(" ")
        array2[i] = words[0]
        array2.insert(i+1, words[1])
    i+=1

count = 0
scount = 0
arr = []
for element in array:
    if count < 8:
        arr.append(element)
        count += 1
    else:
        y.append(arr)
        count = 0
        arr = []
        arr.append(element)
        count += 1
#if team 1 beats team 2 then we add team 1's id. if tie, winner is home.
for item in y:
    if item[4] > item[7]:
        tmp = []
        tmp.append(item[2])
        final.append(tmp)
    else:
        tmp = []
        tmp.append(item[5])
        final.append(tmp)

5602
5602
[['269'], ['127'], ['301'], ['19'], ['59'], ['25'], ['26'], ['32'], ['39'], ['173'], ['42'], ['66'], ['202'], ['334'], ['292'], ['285'], ['121'], ['326'], ['225'], ['118'], ['246'], ['283'], ['305'], ['214'], ['295'], ['141'], ['161'], ['303'], ['168'], ['182'], ['198'], ['250'], ['205'], ['223'], ['229'], ['316'], ['261'], ['329'], ['337'], ['62'], ['252'], ['239'], ['346'], ['70'], ['351'], ['178'], ['180'], ['253'], ['267'], ['309'], ['266'], ['302'], ['236'], ['100'], ['133'], ['148'], ['276'], ['158'], ['164'], ['193'], ['224'], ['235'], ['307'], ['4'], ['45'], ['52'], ['81'], ['137'], ['288'], ['152'], ['220'], ['313'], ['281'], ['278'], ['197'], ['102'], ['222'], ['251'], ['16'], ['82'], ['325'], ['153'], ['181'], ['310'], ['46'], ['48'], ['308'], ['90'], ['113'], ['160'], ['175'], ['60'], ['92'], ['195'], ['10'], ['67'], ['344'], ['279'], ['71'], ['31'], ['78'], ['280'], ['349'], ['287'], ['293'], ['217'], ['246'], ['57'], ['120'], ['319'], ['263'], ['212'], ['126'], 